### ISSUE TITLE
Assessing first production dataset: only 1958?

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/WOA_1degree_monthly-feedstock#2]
@dhruvbalwada, welcome to the feedstock repository created from https://github.com/pangeo-forge/staged-recipes/pull/122.

Our first production [deployment](https://github.com/pangeo-forge/WOA_1degree_monthly-feedstock/deployments/activity_log?environment=production) of this feedstock succeeded. The endpoint URL for accessing this dataset was posted to https://pangeo-forge.org/catalog. (And yes, we _really_ need to improve this bare-bones catalog page!)

Using that URL, we can open the dataset as follows:

```python
import fsspec
import xarray as xr

dataset_public_url = 'https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/WOA_1degree_monthly-feedstock/woa18-1deg-monthly.zarr'
mapper = fsspec.get_mapper(dataset_public_url)
ds = xr.open_zarr(mapper, consolidated=True)
```

In doing this, I noticed that the dataset only spans 12 monthly time steps (just the year 1958): 
```python
ds["time"]
```
```
array([cftime.Datetime360Day(1958, 1, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 2, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 3, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 4, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 5, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 6, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 7, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 8, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 9, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 10, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 11, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(1958, 12, 16, 0, 0, 0, 0, has_year_zero=True)],
      dtype=object)
```

Was this intentional? If not, we can make a PR to update

https://github.com/pangeo-forge/WOA_1degree_monthly-feedstock/blob/main/feedstock/recipe.py

accordingly.

cc @rabernat, and @jbusecke because you were previously following this PR's progress

**Comment by dhruvbalwada** [comment]
Thanks for working on this Charles! Really glad this works now. 

Yes the time axis was intentional (at least the months, the year is arbitrary). The dataset is essentially a monthly climatology - meaning average of all Jan data together, all Feb data together... So 12 time points are correct.

**Comment by cisaacstern** [comment]
Great! So this dataset is ready to go using the url provided in my comment above!

If you find any problems with it, just open an Issue or PR on this repo and tag me. Enjoy.
